"""Launching a program inside whatever terminal emulator the Pi has.

Terminal emulators disagree about how a command is passed: some want
``-e cmd args``, some want ``-- cmd args``, and some want one quoted
string. Rather than encode three quoting dialects, this writes the
command to a small shell script and hands every emulator the same thing
-- a single path to run.
"""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import subprocess
import time
from pathlib import Path

#: Emulator name -> how to build its argv given a script path.
#: Ordered so the Pi OS default (lxterminal) is tried first.
TERMINALS: list[tuple[str, list[str]]] = [
    ("lxterminal", ["-e"]),
    ("x-terminal-emulator", ["-e"]),
    ("xfce4-terminal", ["--command"]),
    ("mate-terminal", ["-e"]),
    ("gnome-terminal", ["--"]),
    ("konsole", ["-e"]),
    ("xterm", ["-e"]),
]

SCRIPT_DIR = Path.home() / ".cache" / "pi-menu" / "launch"
SCRIPT_MAX_AGE = 24 * 60 * 60


class NoTerminalFound(RuntimeError):
    """No terminal emulator is installed."""


def find_terminal() -> tuple[str, list[str]] | None:
    """Return the first installed emulator as ``(path, exec_flags)``."""
    for name, flags in TERMINALS:
        path = shutil.which(name)
        if path:
            return path, flags
    return None


def launch(
    command: list[str],
    title: str = "pi-menu",
    hold: str = "on-error",
    in_terminal: bool = True,
    env: dict[str, str] | None = None,
) -> subprocess.Popen:
    """Start ``command``, in a terminal window when one is available.

    ``hold`` decides whether the window waits for a keypress before
    closing: ``on-error`` only when the program fails, ``always``, or
    ``never``. Raises :class:`NoTerminalFound` if a terminal was asked
    for and none exists.
    """
    environment = {**os.environ, **(env or {})}

    if not in_terminal:
        return subprocess.Popen(command, env=environment)

    terminal = find_terminal()
    if terminal is None:
        raise NoTerminalFound(
            "no terminal emulator found; install lxterminal or xterm "
            "(sudo apt install lxterminal)"
        )

    path, flags = terminal
    script = _write_script(command, title, hold)
    return subprocess.Popen([path, *flags, str(script)], env=environment)


def _write_script(command: list[str], title: str, hold: str) -> Path:
    """Write a runnable wrapper script and return its path."""
    _prune_old_scripts()
    SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    quoted = shlex.join(command)
    hold_block = _hold_block(hold)
    body = f"""#!/bin/sh
# Generated by pi-menu. Safe to delete.
printf '\\033]0;%s\\007' {shlex.quote(title)}
echo "$ {quoted}"
echo
{quoted}
status=$?
echo
if [ "$status" -ne 0 ]; then
    echo "--- {title} exited with status $status ---"
fi
{hold_block}
exit "$status"
"""

    # A distinct name per launch, so two windows never share a script.
    script = SCRIPT_DIR / f"{_safe(title)}-{os.getpid()}-{time.monotonic_ns()}.sh"
    script.write_text(body, encoding="utf-8")
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    return script


def _hold_block(hold: str) -> str:
    prompt = 'printf "Press Enter to close this window... "\n    read _dummy'
    if hold == "always":
        return prompt.replace("\n    ", "\n")
    if hold == "never":
        return ":"
    return f'if [ "$status" -ne 0 ]; then\n    {prompt}\nfi'


def _prune_old_scripts() -> None:
    """Delete wrapper scripts left behind by earlier runs."""
    if not SCRIPT_DIR.is_dir():
        return
    cutoff = time.time() - SCRIPT_MAX_AGE
    for leftover in SCRIPT_DIR.glob("*.sh"):
        try:
            if leftover.stat().st_mtime < cutoff:
                leftover.unlink()
        except OSError:
            pass


def _safe(text: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-") or "app"
