#!/usr/bin/env python3
"""Regenerate ``pi_menu/microcraft/sprites.py`` from the MicroCraft HTML.

The game's art lives in the HTML as five base64 PNGs. The panel wants
plain RGB, and the app should not decode PNGs at start-up or depend on
Pillow at run time, so this reads them once and writes the pixels out as
Python literals. Run it again if the HTML's art changes::

    .venv/bin/python tools/extract_microcraft_sprites.py

Pitch black with zero alpha is transparent and comes out as ``None``.
"""

from __future__ import annotations

import base64
import io
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "MicroCraft — 16×16.html"
OUT = ROOT / "src" / "pi_menu" / "microcraft" / "sprites.py"

#: JS variable -> Python constant.
SHEETS = (
    ("sheet", "BLOCK_SHEET"),
    ("itemSheet", "ITEM_SHEET"),
    ("fluidSheet", "FLUID_SHEET"),
    ("fireSheet", "FIRE_SHEET"),
    ("breakSheet", "BREAK_SHEET"),
    ("uiSheet", "UI_SHEET"),
    ("craftBtnImg", "CRAFT_BUTTON"),
)

HEADER = '''"""The MicroCraft art, one tuple per sheet.

Generated by ``tools/extract_microcraft_sprites.py`` from the PNGs
embedded in the HTML; do not edit by hand. Each sheet is a tuple of rows,
each row a tuple of ``(r, g, b)`` or ``None`` where the source pixel is
transparent. Tiles are 2x2 and addressed by the top-left pixel.
"""

from __future__ import annotations

'''


def decode(html: str, variable: str) -> Image.Image:
    match = re.search(variable + r"\.src = 'data:image/png;base64,([^']+)'", html)
    if match is None:
        raise SystemExit(f"no data URL for {variable} in {HTML.name}")
    return Image.open(io.BytesIO(base64.b64decode(match.group(1)))).convert("RGBA")


def literal(image: Image.Image) -> str:
    width, height = image.size
    rows = []
    for y in range(height):
        cells = []
        for x in range(width):
            r, g, b, a = image.getpixel((x, y))
            cells.append("None" if a == 0 else f"({r}, {g}, {b})")
        rows.append("    (" + ", ".join(cells) + ",),\n")
    return "(\n" + "".join(rows) + ")"


def main() -> int:
    html = HTML.read_text(encoding="utf-8")
    parts = [HEADER]
    for variable, name in SHEETS:
        parts.append(f"{name} = {literal(decode(html, variable))}\n\n")
    OUT.write_text("".join(parts).rstrip("\n") + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
