#!/usr/bin/env python3
"""Solve every level and ship the winning routes as data.

Writes ``src/pi_menu/platformer/routes.py``: one compact string per
level, each character one held-key combination from the solver's
winning playthrough. Auto-play replays these rather than solving,
because the search that takes a second here could take a minute on the
Pi Zero the game actually runs on -- and a shipped route is verified by
the test suite, where a runtime solve is verified by nothing.

Run this after any change to the levels or the physics:

    python3 tools/build_levels.py && python3 tools/solve_routes.py

A stale route fails ``tests/test_platform_routes.py``, which replays
every one of them.
"""

from __future__ import annotations

import concurrent.futures
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "tests"), str(Path(__file__).resolve().parent)]

from pi_menu.platformer.autopilot import KEY_BITS, TICKS_PER_MOVE  # noqa: E402
from pi_menu.platformer.levels import LEVELS  # noqa: E402
from platform_solver import HOLD_TICKS, solve  # noqa: E402

TARGET = ROOT / "src" / "pi_menu" / "platformer" / "routes.py"

HEADER = '''"""The winning route through every level, as solver output.

Generated by ``tools/solve_routes.py`` -- do not edit. Each character
encodes one move as a hex digit of key bits (see
:mod:`pi_menu.platformer.autopilot`), held for ``TICKS_PER_MOVE`` ticks.
The test suite replays every route, so a route that has gone stale --
after a level edit or a physics change -- fails loudly rather than
walking the auto-player into a wall.
"""

from __future__ import annotations

TICKS_PER_MOVE = %d

ROUTES = {
'''


def encode(move: frozenset) -> str:
    bits = 0
    for key, bit in KEY_BITS.items():
        if key in move:
            bits |= bit
    return format(bits, "x")


def solve_one(index: int) -> tuple:
    level = LEVELS[index]
    return level.id, "".join(encode(move) for move in solve(level))


def main() -> int:
    assert TICKS_PER_MOVE == HOLD_TICKS, "autopilot and solver disagree on tempo"
    with concurrent.futures.ProcessPoolExecutor() as pool:
        routes = dict(pool.map(solve_one, range(len(LEVELS))))

    lines = [HEADER % HOLD_TICKS]
    for level in LEVELS:  # keep play order, for readable diffs
        lines.append(f'    "{level.id}": "{routes[level.id]}",')
    lines.append("}")
    lines.append("")
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(routes)} routes to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
